### ISSUE TITLE
Why not embedded?

### ISSUE THREAD

**Issue by janlimpens** [saks/mongoid_acts_as_tree#2]
Hello,

just out of interest: why use references and not embeds in a document database that can do trees very well?

--Jan

**Comment by saberma** [comment]
if you use embed object, while you want to modify the embed object, you must past the parent object id in order to find the that.

Image that, if you have the tree and its level is greater than one, change the leaf object must pass all the parent object id until root object ...

Besides, embeded object in mongoid are hard to re-sort.

**Comment by janlimpens** [comment]
Fair enough, though you are choosing good performance in write operations (rare) at the cost of bad performance concerning reads (not rare at all).
It would be all good, if it was possible to create a tree like index just for reads...
